### PR TITLE
States

### PR DESCRIPTION
**Pull request by Zankoku-Okuno**

### CODE REVIEW

**Comment by chessai** [comment]
Seems a bit out of scope for 'country'. Perhaps this should be its own library?

**Comment by andrewthad** [comment]
I'm fine with having this in `country`. @Zankoku-Okuno is this complete or WIP? And also could you add some tests, particularly just an integration test for encode and decode of any two of the states.

**Comment by Zankoku-Okuno** [comment]
As far as including it here or not, all this stuff is according to the same iso standard, so perhaps fresh documentation would be good.
It's likely usable, but I'm not sure about completeness yet, as I've got to integrate it with freight, and also I made some... design decisions. The rest of the code uses `Text` where I've gone with `ShortText` to better integrate with the l3c stack; there's also a lack of validation in the metaprogram.

**Comment by andrewthad** [comment]
Speaking of `ShortText`, use `UnliftedArray ShortText` instead of `SmallArray ShortText` where possible since it reduces indirections. Beyond that, I guess let's just go ahead and get it integrated with the in-house stuff before thinking further about the design. That may also help ferret out any problems.
Concerning `Text` vs `ShortText`, I think the names may need to be suffixed with `Short`. The alternative would be to do this at the module level (i.e. `Country.Subdivision.ShortText`), and then we could eventually make a `Country.ShortText` module that is consistent with this design. I'm not totally convinced of any particular approach to this horrible issue though. Whenever `text` becomes UTF-8, this will fortunately become a mostly moot point.

**Pull request merged**
