### PR TITLE
Bump upper-bounds to allow aeson-2.0 and attoparsec-0.14

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by chessai** [comment]
@andrewthad can you make a release or revision soon? I'm travelling and won't have time in the near future

**Comment by ocharles** [comment]
Hi @chessai and @andrewthad - any chance of a new release/revision with this soon?

**Comment by andrewthad** [comment]
Released as 0.2.2 today.

**Comment by ocharles** [comment]
Great, thank you!

**Pull request merged**
