### PR TITLE
Use byteslice and bytehash

### PR DESCRIPTION
**Pull request by andrewthad**
I've added a benchmark demonstrating that the changes introduced here make decoding countries from text twice as fast. I've also added more tests to make sure this doesn't regress anything. The only downside is that now, only GHC 8.6 and up will be supported, but I'm not too concerned about that. Anyone needing to use older GHCs can just stay on version `0.2`. This cannot be merged until `bytehash` is released.

### CODE REVIEW

**Comment by chessai** [comment]
nice

**Comment by chessai** [comment]
jesus christ.

you know this library is probably used by windows users, right? if not now, i can foresee it happening soon. this is the most popular country library, as far as i can tell. it's probably worthwhile to CPP this PR.

**Comment by andrewthad** [comment]
I'm skeptical that anyone is building this on windows although I'd love to be wrong. I've switch to using the `entropy` library, which has an an almost disturbing level of cross-platform support including ghcjs and HaLVM, for a better cross-platform story. Still, in an ideal world, I would rather just be able to write something like:

```
case x of
  "united states"# -> unitedStates
  "usa"# -> unitedStates
  "mexico"# -> mexico
  ...
```

Hopefully, I can add this to GHC one day, but until then, good ol' `unsafePerformIO` gets the job done reasonably well.

**Comment by andrewthad** [comment]
The windows problems should be gone since `entropy` is cross-platform. Merging.

**Pull request merged**
